[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
crust8_core = { path = "../crust8_core" }
eframe = "0.32.0"
clap = { version = "4.5.43", features = ["derive"] }
anyhow = "1.0.98"

[[bin]]
name = "crust8"
path = "src/main.rs"